version: "3.7"

services:
  account_database:
    image: mysql:5.7
    platform: linux/amd64
    container_name: account_db
    environment:
      MYSQL_DATABASE: account
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - account_network

  account_application:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - account_database
    container_name: account_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://account_database:3306/account
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - account_network

networks:
  account_network:
    driver: bridge

